# exercise 1

In [1]:
# import numpy in this cell

In [2]:
# create a 1-d numpy array (call it ts for timestamps), with increasing integers from 3 to 300 
# (including 3 but not 300) with increment of 3, and print the array

In [3]:
# change the dtype of ts into 32-bit floating point and pring ts

In [4]:
# add 0.5 to every element in ts which is larger than 200 and print ts

In [5]:
# find out the mean difference between adjacent elements and print it
# it should be 3.0051

In [6]:
# find the index of the element closest to the number 212.3, and print that index and print the element
# you should see: 
# index: 70 ; value: 213.5

# exercise 2

In [7]:
# create a 2-d matrix with 5 rows and 10 columns and every element equals to 0

In [8]:
# print the data type of frame
# you should see:
# float64

In [9]:
# change the dtype of frame to unsigned 16-bit integer

In [10]:
# cange the element at 4th row and 9th column into 5, and print frame
# you should see:
# [[0 0 0 0 0 0 0 0 0 0]
#  [0 0 0 0 0 0 0 0 0 0]
#  [0 0 0 0 0 0 0 0 0 0]
#  [0 0 0 0 0 0 0 0 5 0]
#  [0 0 0 0 0 0 0 0 0 0]
#  [0 0 0 0 0 0 0 0 0 0]]

In [11]:
# change the elements in the square between 2nd and 4th row (including 2nd but not 4th), 4th and 6th 
# column (including 4th but not 6th) into 3, then print frame
# you should see:
# [[0 0 0 0 0 0 0 0 0 0]
#  [0 0 0 3 3 0 0 0 0 0]
#  [0 0 0 3 3 0 0 0 0 0]
#  [0 0 0 0 0 0 0 0 5 0]
#  [0 0 0 0 0 0 0 0 0 0]
#  [0 0 0 0 0 0 0 0 0 0]]

In [12]:
# change every element in the first row into 7, print frame
# verify the result in the printed matrix
# you should see:
# [[7 7 7 7 7 7 7 7 7 7]
#  [0 0 0 3 3 0 0 0 0 0]
#  [0 0 0 3 3 0 0 0 0 0]
#  [0 0 0 0 0 0 0 0 5 0]
#  [0 0 0 0 0 0 0 0 0 0]
#  [0 0 0 0 0 0 0 0 0 0]]

In [13]:
# change every element in the 7th column into 3, print frame
# you should see:
# [[7 7 7 7 7 7 3 7 7 7]
#  [0 0 0 3 3 0 3 0 0 0]
#  [0 0 0 3 3 0 3 0 0 0]
#  [0 0 0 0 0 0 3 0 5 0]
#  [0 0 0 0 0 0 3 0 0 0]
#  [0 0 0 0 0 0 3 0 0 0]]

In [14]:
# print the mean value of every element in frame
# you should see:
# 1.63333333333

In [15]:
# print mean value of each row
# you should see:
# [ 6.6  0.9  0.9  0.8  0.3  0.3]

In [16]:
# print mean value of each column
# you should see:
# [ 1.16666667  1.16666667  1.16666667  2.16666667  2.16666667  1.16666667
#   3.          1.16666667  2.          1.16666667]

In [17]:
# make a new matrix frame2, with every element equals the equvalent element in frame plus 1
# print frame2
# you should see:
# [[8 8 8 8 8 8 4 8 8 8]
#  [1 1 1 4 4 1 4 1 1 1]
#  [1 1 1 4 4 1 4 1 1 1]
#  [1 1 1 1 1 1 4 1 6 1]
#  [1 1 1 1 1 1 4 1 1 1]
#  [1 1 1 1 1 1 4 1 1 1]]

In [18]:
# attach frame and frame2 into a 3-d matrix with depth of 2, call it frames
# print frames
# you should see:
# [[[7 7 7 7 7 7 3 7 7 7]
#   [0 0 0 3 3 0 3 0 0 0]
#   [0 0 0 3 3 0 3 0 0 0]
#   [0 0 0 0 0 0 3 0 5 0]
#   [0 0 0 0 0 0 3 0 0 0]
#   [0 0 0 0 0 0 3 0 0 0]]
# 
#  [[8 8 8 8 8 8 4 8 8 8]
#   [1 1 1 4 4 1 4 1 1 1]
#   [1 1 1 4 4 1 4 1 1 1]
#   [1 1 1 1 1 1 4 1 6 1]
#   [1 1 1 1 1 1 4 1 1 1]
#   [1 1 1 1 1 1 4 1 1 1]]]

In [19]:
# print the shape of frames
# you should see:
# (2L, 6L, 10L)

# exercise 3

In [20]:
# import matplotlib.pyplot as plt
import matplotlib.pyplot as plt

%matplotlib inline

In [21]:
# create a 1-d numpy array (call it t for time), with increasing 64-bit floating point number from 0 
# to 3 (including 0 but not 3) with increment of 0.001
# print the first 10 elements of t
# print the last 10 elements of t
# print the length of t

# you should see:
# [ 0.    0.01  0.02  0.03  0.04  0.05  0.06  0.07  0.08  0.09]
# [ 2.9   2.91  2.92  2.93  2.94  2.95  2.96  2.97  2.98  2.99]
# 300

In [22]:
# lets say t is a 3-second time axis, calculate the sampling rate of t, call it fs
# print fs
# you should see:
# 100

In [23]:
# create a 1-d array representing a sinusoid wave with amplitude of 2, frequenc of 1 Hz and phase of 0
# on t axis, call it sin1
# plot sin1 against t

In [24]:
# creat a function to generate a customized sinusoid wave on any arbituary time axis with unit of second
# call the function: sinusoid
# the input of the function should be:
# t: time axis (in second)
# freq: frequency (default 1)
# amp: amplitude (default 1)
# phase: phase (in degree, default 0)
# dc: DC component, default 0

In [25]:
# use sinusoid function to generate a sinusoid wave (frequency 3 Hz, amplitude 3, phase 90 degree,
# dc 0) on time axis t, call it sin2
# plot sin2 against t

In [26]:
# use sinusoid function to generate a sinusoid wave (frequency 5 Hz, amplitude 0.5, phase 180 degree,
# dc 0) on time axis t, call it sin3
# plot sin3 against t

In [27]:
# create a 1-d array (call it noise) with same dimension of t and random number following a flat 
# distribution from -0.5 to 0.5, call it noise
# plot noise against t

In [28]:
# generate a 1-d array (call it signal) by adding sin1, sin2, sin3 and noise together
# plot signal against t

In [29]:
# plot fist 0.5 second of the signal

In [30]:
# plot fft of the signal in the frequency range [0, 10] Hz
# you should see three peaks at 1, 3 and 5 Hz.